In [16]:
count = 10**2
nums = []
for i in range(count):
    nums.append(i)
nums.reverse()
print(nums)

[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [15]:
count = 10**2
nums=[]
for i in range(count):
    nums.insert(0,i)
print(nums)

[99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [18]:
class Node:
    def __init__(self, value, next = None):
        self.value = value
        self.next = next
L = Node("a",Node("b",Node("c",Node("d"))))
L.next.next.next.value

'd'

In [20]:
import timeit
timeit.timeit("x=2+2")
timeit.timeit("x=sum(range(10))")

0.6360825509400261

In [23]:
hash(42)
hash("hello,world!")

4457642062143785016

In [26]:
a,b,c,d,e,f,g,h=range(8)
N=[
    {b,c,d,e,f}, #a
    {c,e},#b
    {d},#c
    {e},#d
    {f},#e
    {c,g,h},#f
    {f,h},#g
    {f,g}#h
]
print(N)
print(b in N[a])
print(len(N[f]))

[{1, 2, 3, 4, 5}, {2, 4}, {3}, {4}, {5}, {2, 6, 7}, {5, 7}, {5, 6}]
True
3


In [27]:
a,b,c,d,e,f,g,h=range(8)
N=[
    [b,c,d,e,f], #a
    [c,e],#b
    [d],#c
    [e],#d
    [f],#e
    [c,g,h],#f
    [f,h],#g
    [f,g]#h
]
print(N)
print(b in N[a])
print(len(N[f]))

[[1, 2, 3, 4, 5], [2, 4], [3], [4], [5], [2, 6, 7], [5, 7], [5, 6]]
True
3


In [34]:
a,b,c,d,e,f,g,h=range(8)
N=[
    {b:2,c:1,d:3,e:9,f:4}, #a
    {c:4,e:3},#b
    {d:8},#c
    {e:7},#d
    {f:5},#e
    {c:2,g:2,h:2},#f
    {f:1,h:6},#g
    {f:9,g:8}#h
]
print(N)
print(b in N[a])
print(len(N[f]))
print(a,b)
print(N[a][b])

[{1: 2, 2: 1, 3: 3, 4: 9, 5: 4}, {2: 4, 4: 3}, {3: 8}, {4: 7}, {5: 5}, {2: 2, 6: 2, 7: 2}, {5: 1, 7: 6}, {5: 9, 6: 8}]
True
3
0 1
2


In [37]:
a,b,c,d,e,f,g,h=range(8)
N={
    'a':set('bcdef'),
    'b':set('ce'),
    'c':set('d'),
    'd':set('e'),
    'e':set('f'),
    'f':set('cgh'),
    'g':set('fh'),
    'h':set('fg')
    }
print(N)


{'a': {'b', 'e', 'f', 'c', 'd'}, 'b': {'c', 'e'}, 'c': {'d'}, 'd': {'e'}, 'e': {'f'}, 'f': {'g', 'h', 'c'}, 'g': {'f', 'h'}, 'h': {'g', 'f'}}


In [41]:
a,b,c,d,e,f,g,h=range(8)
N=[
    [0,1,1,1,1,1,0,0], #a
    [0,0,1,0,1,0,0,0],#b
    [0,0,0,1,0,0,0,0],#c
    [0,0,0,0,1,0,0,0],#d
    [0,0,0,0,0,1,0,0],#e
    [0,0,1,0,0,0,1,1],#f
    [0,0,0,0,0,0,0,1],#g
    [0,0,0,0,0,1,1,0]#h
]
print(N)
print(b in N[a])
print(len(N[f]))
print(N[a][b])
print(sum(N[f]))

[[0, 1, 1, 1, 1, 1, 0, 0], [0, 0, 1, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 1, 1, 0]]
True
8
1
3


In [49]:
a,b,c,d,e,f,g,h=range(8)
_=float('inf')
N=[
    [0,2,1,3,9,4,_,_], #a
    [_,0,4,_,3,_,_,_],#b
    [_,_,0,8,_,_,_,_],#c
    [_,_,_,0,7,_,_,_],#d
    [_,_,_,_,0,5,_,_],#e
    [_,_,2,_,_,0,2,2],#f
    [_,_,_,_,_,1,0,6],#g
    [_,_,_,_,_,9,8,0]#h
]
print(N)
print(b in N[a])
print(len(N[f]))
print(N[a][b])
print(sum(N[f]))

print(N[a][b]<_)
print(N[c][e]<_)
print(sum(1 for n in N[a] if n < _))

[[0, 2, 1, 3, 9, 4, inf, inf], [inf, 0, 4, inf, 3, inf, inf, inf], [inf, inf, 0, 8, inf, inf, inf, inf], [inf, inf, inf, 0, 7, inf, inf, inf], [inf, inf, inf, inf, 0, 5, inf, inf], [inf, inf, 2, inf, inf, 0, 2, 2], [inf, inf, inf, inf, inf, 1, 0, 6], [inf, inf, inf, inf, inf, 9, 8, 0]]
True
8
2
inf
True
False
6


In [51]:
#numpy
n = [[0] * 10 for i in range(10)]
print(n)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]


In [53]:
import numpy as np
n = np.zeros([10,10])
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [55]:
t=[["a","b"],["c"],["d",["e","f"]]]
print(t[0][1])
print(t[2][1][0])

b
e


In [56]:
class Tree:
    def __init__(self,left,right):
        self.left = left
        self.right = right
t=Tree(Tree("a","b"),Tree("c","d"))
t.right.left

'c'

In [60]:
class Tree:
    def __init__(self,kids,next = None):
        self.kids = self.val=kids
        self.next = next
t=Tree(Tree("a",Tree("b",Tree("c",Tree("d")))))
t.kids.next.next.kids
t.kids.next.next.val

'c'